### ISSUE TITLE
Controlling iteration speed of the machine

### ISSUE THREAD

**Issue by WannaBeKratos** [LekKit/RVVM#109]
Hi, is it possible to control the event loop, looking through the public API I did not see a feature like that, is it a feature being considered ?

**Comment by LekKit** [comment]
It is not possible to precisely count CPU cycles as it would be wasteful performance wise.
It is however possible to limit host CPU usage using this API:
`rvvm_set_opt(machine, RVVM_OPT_MAX_CPU_CENT, 40)`
Which means "guest CPU may only run for 40% of the host CPU time quant"

The eventloop has no relation to this as it handles IO-related stuff and timekeeping, but vCPU are separate threads
