### ISSUE TITLE
Asking for SDL debug output support

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [LekKit/RVVM#119]
Currently I'm porting RVVM to a sony walkman nw-zx300. I closed all processes using `/dev/graphics/fb0` and it's possible to use cat to write to `/dev/graphics/fb0` now. However, RVVM just didn't worked and I got a blank black screen. It seems to be a problem of SDL, not the kernel or framebuffer device since the picture on the screen was wiped out, so I wanted to see the SDL's output. It seems that RVVM's `--verbose` option didn't print the debug output given by SDL, will we add it later?

**Comment by LekKit** [comment]
Do you mean enabling verbose SDL mode by RVVM `-v` argument? Yea could do that, for now I'd use an env like `SDL_DEBUG` or the likes, and AFAIK for full verbosity you have to rebuild SDL

**Comment by fish4terrisa-MSDSM** [comment]
> Do you mean enabling verbose SDL mode by RVVM `-v` argument? Yea could do that, for now I'd use an env like `SDL_DEBUG` or the likes, and AFAIK for full verbosity you have to rebuild SDL

That's what I mean. And, I have already found the bug, which is a missing of `/etc/fb.modes`. However, after writen that file, RVVM just didn't output anything on the screen. I'm currently working on it. (If I only start rvvm with opensbi, will I see the output on the screen?)

**Comment by LekKit** [comment]
> If I only start rvvm with opensbi, will I see the output on the screen?)

You should see RVVM splash logo that is drawn before guest takes over the framebuffer.

**Comment by LekKit** [comment]
Enabled `SDL_DEBUG` by default in a1f2f9c
