### ISSUE TITLE
Asking for RVVM as a ELF loader

### ISSUE THREAD

**Issue by fewletter** [LekKit/RVVM#121]
I am currently modifying the RVVM as a elf loader. I am now struggling with a problem that I don't know how to execute a program on the machine. I've noticed that the `bincopy` in the elf_load is to read the elf file and map into the machine's memory, but does RVVM has the feature of running a program or I should modify RVVM. Besides, should I create a userspace to run the elf file, because I see that there is no userspace in RVVM or I misunderstand it.
Any hint is good, I have think for this problem for a while.

**Comment by LekKit** [comment]
The `elf_load.c` library has 2 modes of function:
- Userland mapping (loading any foreign ELF into the RVVM process address space, as if it would be done with a native userland binary)
- Objcopy (Same what `objcopy` from binutils does, i.e. unpack a flat binary out of the ELF which is widely used for loading ELF firmware/kernels, stuff like vmlinux)

Currently ony the second one is used upstream - when you pass the machine a firmware/kernel image that identifies as an ELF, it automatically does objcopy on it into the system RAM where that image should be loaded, as does QEMU for example.

The other mode is exactly what you're looking for if you want to *just* load the ELF into the process address space. To use it, pass a `NULL` as `base` in `elf_desc_t` description in `elf_load_file()`:
```c
elf_desc_t elf = {
    .base = NULL,
};
rvfile_t* file = rvopen(argv[0], 0); // RO access is enough
if (!file || !elf_load_file(file, &elf)) {
    rvvm_error("Failed to load ELF %s", argv[0]);
    ...
}

rvvm_warn("ELF entry point at %lx", elf.entry);
// Interpreter is usually ld-linux.so for dynamically linked ELFs, absent for static ELFs
if (elf.interp_path) rvvm_warn("ELF interpreter: %s", elf.interp_path);
```

Now if you want to actually run those ELFs as RISC-V userland, that's only halfway done (and would be perfect if someone stepped in to help). There is userland VM API documented at the bottom of `rvvmlib.h` which allows to create emulated userland thread context, read/write CPU registers of that thread and let it run until it reaches an `ecall` instruction (or any other virtual CPU exception happens, altho if the guest code misbehaves in userland you might as well get a SEGV on your whole process).

This userland API is already used in a HaikuOS project "UserlandVM" which emulates Haiku RISC-V binaries on a foreign arch Haiku host, so it is proven to work for even somewhat complicated threaded GUI apps.

The part that is missing to run Linux binaries, is to emulate all the Linux syscalls upon handling that `ecall` trap, and setting stuff like guest process stack, `argv`/`envp`, AT_PHDRs. I am already working on a WIP userland emulator for a while - the latter part somehow trips me up: I can't get any dynamic binary to work properly and it crashes somewhere down the road upon parsing those AT_PHDR fields, etc. Static binaries execute kinda OK.
Should I start upstreaming my work, even if it's this half-baked? I guess someone might be able to debug what's wrong, there is also libriscv project which does exactly this so maybe we can get some clues from there

**Comment by fewletter** [comment]
Thanks for replying that detail. I am interested in your work even it’s half done and I’d like to help with the problem of running elf in userland. Also I’d to check out the libriscv project you mentioned above.

**Comment by LekKit** [comment]
Some spoilers (Soon will be merging this)

![image](https://github.com/LekKit/RVVM/assets/50500857/02824fc5-db61-4e7c-a13e-db61204883ab)

**Comment by LekKit** [comment]
See cdfea8b

**Comment by LekKit** [comment]
Oh, so I figured why the x86 jump_start() didn't work, now we can chain-load x86 dynamic ELFs from RVVM code without problems. Sadly RISC-V dyn ELFs still crash...

![image](https://github.com/LekKit/RVVM/assets/50500857/2b774785-54e0-4137-8fca-ddec47825243)

**Comment by fewletter** [comment]
Thanks for your work. I can check the with my elf file later.

**Comment by LekKit** [comment]
Can we move this discussion to #56?

**Comment by fewletter** [comment]
Sure, fine.
