### ISSUE TITLE
plugin architecture ?

### ISSUE THREAD

**Issue by ZLangJIT** [LekKit/RVVM#159]
- would allow for quick prototyping of rvvm specific additions without needing to modify rvvm codebase
- users would not need to pull updates and resolve conflicts to test their changes against the latest source
- users must pull/resolve if new hooks are to be added/tested in the plugin architecture, but once hooks are added, all existing plugins need only implement such callbacks
- stub callbacks must be given for any plugins not supplying wanted callbacks to reduce boilerplate plugin code
- users may later integrate their plugin directly into rvvm code base for optimizations that would not be possible via the plugin architecture

**Comment by ZLangJIT** [comment]
hmm maybe not as it may be too complex to maintain, eg a user may want to plug into many subsystems/devices via plugins and may be better off just forking/modifying the codebase instead

**Comment by LekKit** [comment]
`librvvm` API doesn't imply that device implementation shall live in the same library, it can be registered wherever you want, same for I2C/PCI/HID devices, etc
