### ISSUE TITLE
Booting an ISO

### ISSUE THREAD

**Issue by human222** [LekKit/RVVM#166]
User error, nvm

**Comment by LekKit** [comment]
ISO are simply raw image files but with different extension. They can be attached via `-i debian.iso` argument, but you also need a working U-Boot firmware (`fw_payload.bin`) as described in the wiki: https://github.com/LekKit/RVVM/wiki/Running#recommended-vm-firmware

Note that being able to actually boot the ISO depends on the guest having drivers for RVVM machine (Mostly everything that works on QEMU or HiFive Unmatched boards works on RVVM)

**Comment by human222** [comment]
Thanks, I got it to boot. It doesn't respond to keyboard input, but that might be a Debian issue.

**Comment by LekKit** [comment]
> Thanks, I got it to boot. It doesn't respond to keyboard input, but that might be a Debian issue.

Upstream Debian kernel has I2C-HID & SiFive I2C kernel modules disabled (RVVM currently exposes input as I2C-HID). So basically drivers are disabled and you are better off with uart console or SSH for now. The long term fix would be enabling drivers in question in upstream Debian kernel package, or switching to XHCI USB HID altogether on RVVM side.
