### ISSUE TITLE
Failed to build openSBI.

### ISSUE THREAD

**Issue by OliveLake** [LekKit/RVVM#44]
Hi, I have built risc-v linux toolchain, linux kernel, and uBoot, and try to build openSBI.
After generate `fw_jump.bin` in `opensbi/build/platform/generic/firmware`
`./rvvm_riscv fw_jump.bin -kernel linux_Image -image rootfs.img -rv64 -mem 2G -smp 2 -res 1280x720`
It will loop forever, like this 
<img width="412" alt="OpenSBI" src="https://user-images.githubusercontent.com/52832181/149742075-1c6062d7-30d4-4e59-8a89-35630b1f2e69.png">

Is this problem is caused by openSBI or RVMM and how can I successfully execute RVMM?

many thanks!

**Comment by LekKit** [comment]
Hi, it looks like you are running U-Boot as SBI payload, and U-Boot tries to access MMC flash - RVVM doesn't support flash (yet), so U-Boot resets the VM.
We have support for IDE (ATA) hard-drives, you may need to build U-Boot with IDE support, and we have future plans for NVME/MMC support.
You also can boot the Linux kernel directly after SBI, without U-Boot (that's what -kernel option is for), and it's easier. I've attached working RV64 & RV32 kernels and a config if you wanna build one yourself.
Hope that helps!
[kernels.zip](https://github.com/LekKit/RVVM/files/7892861/kernels.zip)

**Comment by OliveLake** [comment]
@LekKit 
Thank you for replying!
I've remake OpenSBI without U-Boot, and use your attachment RV32 kernel (Thanks again!)
`./rvvm_riscv fw_jump.bin -kernel linux_rv32 -mem 1G -res 1280x720`

![RVVM1](https://user-images.githubusercontent.com/52832181/150092527-99079646-e981-4fcf-b3bb-d6e786b69d8f.png)
and then 
![RVVM2](https://user-images.githubusercontent.com/52832181/150105385-dbba17da-65a4-41d6-a2df-161c03d363d5.png)


It seems like kernel cannot communicate with my hard drive?

**Comment by LekKit** [comment]
It looks like you didn't pass any hard drive image to RVVM (option -image [file]), you need a rootfs image with your desired distribution (your own physical hard drive would be of no use here - it probably doesn't have any riscv binaries to begin with).
For RV32, I'd recommend using Buildroot (https://buildroot.org/), there aren't that many pre-built distributions for 32-bit RISC-V. After building, the image would be at output/images/rootfs.ext2 from base directory. I've also attached a working image that I have built previously for testing (unpack it and use with -image buildroot_rv32.img): [buildroot_rv32.zip](http://lekkit.hopto.org:8080/rvvm-images/riscv32/buildroot_rv32.zip), login: root, password: riscv
For RV64 there are plenty of prebuilt distributions like Alpine, Debian, Fedora, Ubuntu, SUSE, Arch.
You may also create your own rootfs from some tarball or etc, like this:
```
dd if=/dev/zero of=rootfs.img bs=1M count=256 (put image size in megabytes here)
/sbin/mkfs.ext4 rootfs.img
mkdir mnt
sudo mount rootfs.img mnt
(now put everything you need as rootfs into mnt directory)
sudo umount mnt
sync
```

You'd then use the resulting image by passing -image rootfs.img to RVVM
Glad to help!

**Comment by LekKit** [comment]
Closed due to inactivity, fell free to open another issue if you have more questions
