### ISSUE TITLE
Online demo: kernel panic

### ISSUE THREAD

**Issue by X547** [LekKit/RVVM#69]
```
[    8.477060] /dev/root: Can't open blockdev
[    8.570120] VFS: Cannot open root device "nvme0n1" or unknown-block(0,0): error -6
[    8.740940] Please append a correct "root=" boot option; here are the available partitions:
[    8.914860] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    9.073880] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0) ]---
```

**Comment by LekKit** [comment]
Yeah that's unfortunate... The wasmfs seemingly broke (It's used for lazy loading of file parts, as opposed to preloading the entire rootfs at page load time)
Will try to fix

**Comment by LekKit** [comment]
Updated, see if it works now. Lazy binary data loading seemingly doesn't work for everyone, so it has to preload a tiny buildroot fs instead.

**Comment by X547** [comment]
> Updated, see if it works now.

Yes, it works now.
