### ISSUE TITLE
Asking for more serial ports

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [LekKit/RVVM#86]
(sorry for my broken english...)
I made a project of a emulator on android ,which runs archlinux riscv on android using RVVM.The project is [archriscv-term](https://github.com/fish4terrisa-MSDSM/archriscv-term).The problem is that there is only one tty available.Could you add more serial ports? You may bind them to some sockets so that I can connect them using socat.

**Comment by LekKit** [comment]
I tried to add multiple serial ports previously, they were fine hardware-wise but the system didn't care to put kernel console or `logind` on them. Any help guest-side is appreciated.

**Comment by fish4terrisa-MSDSM** [comment]
Try `systemctl enable --now getty@ttyS1.service`.It will work .(Tested in qemu)

**Comment by LekKit** [comment]
Any suggestions for a nice serial device API? Doing sth similar to `tap_api` would require an internal ring buffer, hence I imagine sth like this instead:
- `serial_write()` called from uart and writes to device (TX)
- `serial_read()` called from uart and reads bytes from device (RX)
- `serial_notify()` called from device side to notify there are bytes to receive (Basically a software interrupt)

@iyzsong is working on basically same thing, see #85 (And mentioned uart sockets) so I won't touch `ns16550a` for now to prevent merge conflicts. The serial API will be reviewed considering anything we will came up with. Stay tuned X)

**Comment by LekKit** [comment]
FYI: I will be posting Linux kernel configs and stuff soon (Also working on a proper RVVM U-Boot support) so you can build newer mainline kernels without copying my old builds around

**Comment by fish4terrisa-MSDSM** [comment]
> FYI: I will be posting Linux kernel configs and stuff soon (Also working on a proper RVVM U-Boot support) so you can build newer mainline kernels without copying my old builds around

Hurry ,that really helps me .Its hard to recompile the mainline kernel of arch.(It has took me more than 1 day to compile in archriscv-term with rvvm)

**Comment by LekKit** [comment]
> Its hard to recompile the mainline kernel of arch.(It has took me more than 1 day to compile in archriscv-term with rvvm)

See https://github.com/LekKit/patches-misc for a minimal kernel config, U-Boot patch, etc useful things. I haven't decided where to post binary builds yet.

Use a `riscv64-linux-gnu` crosscompiler toolchain natively on your computer, compiling in a VM is going to be several times slower. It is available on many distributions including Arch or Debian-based distros.
It is also possible to build the kernel in CI, but I haven't looked into it yet.

**Comment by fish4terrisa-MSDSM** [comment]
> > Its hard to recompile the mainline kernel of arch.(It has took me more than 1 day to compile in archriscv-term with rvvm)
> 
> See https://github.com/LekKit/patches-misc for a minimal kernel config, U-Boot patch, etc useful things. I haven't decided where to post binary builds yet.
> 
> Use a `riscv64-linux-gnu` crosscompiler toolchain natively on your computer, compiling in a VM is going to be several times slower. It is available on many distributions including Arch or Debian-based distros. It is also possible to build the kernel in CI, but I haven't looked into it yet.

I will try the u-boot patch later.But for the kernel....it may cause some problems when the kernel is not the same as mainline kernel (especially in some kernel modules in the arch repo...)

**Comment by LekKit** [comment]
> I will try the u-boot patch later.But for the kernel....it may cause some problems when the kernel is not the same as mainline kernel (especially in some kernel modules in the arch repo...)

It is specifically a tiny static kernel without modules which is supposed to be directly passed into RVVM `-k` option, work independently of distro, boot faster and require less space. It is mainline, there are no patches needed. It is just smol.

If you need a repo kernel, just use the one from repos - it shoud work (But it is also a more complicated boot flow, like SBI->U-Boot->(GRUB?)->Linux, uses initramfs, etc) so it is harder to bring up.

Also see this: https://github.com/LekKit/patches-misc/releases

**Comment by fish4terrisa-MSDSM** [comment]
> > I will try the u-boot patch later.But for the kernel....it may cause some problems when the kernel is not the same as mainline kernel (especially in some kernel modules in the arch repo...)
> 
> It is specifically a tiny static kernel without modules which is supposed to be directly passed into RVVM `-k` option, work independently of distro, boot faster and require less space. It is mainline, there are no patches needed. It is just smol.
> 
> If you need a repo kernel, just use the one from repos - it shoud work (But it is also a more complicated boot flow, like SBI->U-Boot->(GRUB?)->Linux, uses initramfs, etc) so it is harder to bring up.
> 
> Also see this: https://github.com/LekKit/patches-misc/releases

Thank you ,the u-boot image really helps.I will try it later.

**Comment by LekKit** [comment]
How to boot Arch Linux repo kernel from U-Boot (If you really want it):
1. Ensure your image has a GPT partition table
2. Ensure your distro is installed on the first partition and the FS is ext4
3. `pacman -S linux`
4. Put this into `/boot/extlinux/extlinux.conf:

```
## /boot/extlinux/extlinux.conf

default l0
menu title U-Boot menu
prompt 0
timeout 50

label l0
        menu label Arch Linux RISC-V
        linux /boot/vmlinuz-linux
        initrd /boot/initramfs-linux.img

        append rw noquiet root=/dev/nvme0n1p1

label l0r
        menu label Arch Linux RISC-V (rescue target)
        linux /boot/vmlinuz-linux
        initrd /boot/initramfs-linux-fallback.img

        append rw noquiet single root=/dev/nvme0n1p1
```

You can use a separate `/boot` partition for this, but it is wasteful if it works like that already. Also use UUID instead of device name if possible.
It is also possible to use GRUB EFI, but the version currently in Arch repos is broken on RISC-V and overall the U-Boot script is pretty standard on existing RISC-V distro images

```
[root@archlinux ~]# lspci
00:00.0 Host bridge: SiFive, Inc. FU740-C000 RISC-V SoC PCI Express x8 to AXI4 Bridge
00:01.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8169 PCI Gigabit Ethernet Controller
00:02.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mach64 VT4 [Video Xpression+]
00:03.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 980
[root@archlinux ~]# uname -a
Linux archlinux 6.2.1-arch1-1 #1 SMP PREEMPT Wed, 01 Mar 2023 18:56:17 +0000 riscv64 GNU/Linux
```

No drivers for I2C HID(
Arch Linux RISC-V maintainers should enable driver for OpenCores I2C controller. It is also present on the HiFive Unmatched board and different SiFive SoCs.
```
[root@archlinux ~]# dmesg | grep i2c
[root@archlinux ~]# dmesg | grep hid
[    1.872194] hid: raw HID events driver (C) Jiri Kosina
[root@archlinux ~]# i2cdetect -y 0
Error: Could not open file `/dev/i2c-0' or `/dev/i2c/0': No such file or directory
```

**Comment by LekKit** [comment]
Asked about I2C support in matrix, should be resolved soon
![image](https://user-images.githubusercontent.com/50500857/231259346-835c7e4c-1913-49ff-af49-7d06c5fc9a95.png)

**Comment by fish4terrisa-MSDSM** [comment]
> > > I will try the u-boot patch later.But for the kernel....it may cause some problems when the kernel is not the same as mainline kernel (especially in some kernel modules in the arch repo...)
> > 
> > 
> > It is specifically a tiny static kernel without modules which is supposed to be directly passed into RVVM `-k` option, work independently of distro, boot faster and require less space. It is mainline, there are no patches needed. It is just smol.
> > If you need a repo kernel, just use the one from repos - it shoud work (But it is also a more complicated boot flow, like SBI->U-Boot->(GRUB?)->Linux, uses initramfs, etc) so it is harder to bring up.
> > Also see this: https://github.com/LekKit/patches-misc/releases
> 
> Thank you ,the u-boot image really helps.I will try it later.

I tried the fw_payload.bin ,it worked well for archlinux riscv .Thank you.

**Comment by fish4terrisa-MSDSM** [comment]
> > > > I will try the u-boot patch later.But for the kernel....it may cause some problems when the kernel is not the same as mainline kernel (especially in some kernel modules in the arch repo...)
> > > 
> > > 
> > > It is specifically a tiny static kernel without modules which is supposed to be directly passed into RVVM `-k` option, work independently of distro, boot faster and require less space. It is mainline, there are no patches needed. It is just smol.
> > > If you need a repo kernel, just use the one from repos - it shoud work (But it is also a more complicated boot flow, like SBI->U-Boot->(GRUB?)->Linux, uses initramfs, etc) so it is harder to bring up.
> > > Also see this: https://github.com/LekKit/patches-misc/releases
> > 
> > 
> > Thank you ,the u-boot image really helps.I will try it later.
> 
> I tried the fw_payload.bin ,it worked well for archlinux riscv .Thank you.

I want to include it to my project archriscv-term ,is that ok?

**Comment by LekKit** [comment]
> I want to include it to my project archriscv-term ,is that ok?

Yep. Just point at my patch repo somewhere in your repo to comply with the GPL license of U-Boot

**Comment by LekKit** [comment]
Possible design of new RVVM arguments:
- `rvvm ...` brings UART over terminal as uausl
- `rvvm ... -serial /tmp/pts1` brings the same UART over PTY/pipe path
- `rvvm ... -serial stdout -serial /tmp/pts1 -serial /tmp/pts2` (Myriad of different uarts over different endpoints)

@iyzsong does this look good to you?

![image](https://user-images.githubusercontent.com/50500857/235312683-8acef717-f4db-4936-883f-096d5305c213.png)

**Comment by LekKit** [comment]
UPD: Seems fine usable for KGDB as well, yay

I hope for some feedback if everything is working as you wished, and if the issue may be closed
Howto:
```
socat pty,rawer,link=/tmp/pts1 stdio,rawer
rvvm ... -serial /tmp/pts1
```

It is also possible to use RVVM API from JNI and directly wire the chardev into Java code where you handle the TTYs, altho I have very little idea about doing JNI bindings the proper way (Any suggestions?)

**Comment by ghost** [comment]
Look great!

> rvvm ... -serial stdout -serial /tmp/pts1 -serial /tmp/pts2

There are some ambiguities here, stdin was used too.
how about `rvvm ... -serial stdio -serial file:/tmp/pts1 -serial file:/tmp/pts2`?

**Comment by LekKit** [comment]
> There are some ambiguities here, stdin was used too. how about `rvvm ... -serial stdio -serial file:/tmp/pts1 -serial file:/tmp/pts2`?

The only ambiguity would be if you have a file `stdout` in your local directory. About "stdin was used too": Technically, they are the same file, but opened multiple times as different FDs.

I can support both syntaxes if you wish, I just don't wanna overcomplicate it like QEMU with their 9999 parts comprising of an argument (Ever remember how to attach nvme properly? :D)

**Comment by ghost** [comment]
> they are the same file, but opened multiple times as different FDs.

Okay, thanks.

> I can support both syntaxes if you wish, I just don't wanna overcomplicate it like QEMU with their 9999 parts comprising of an argument (Ever remember how to attach nvme properly? :D)

No problem, current is fine.

**Comment by fish4terrisa-MSDSM** [comment]
> Possible design of new RVVM arguments:
> 
> * `rvvm ...` brings UART over terminal as uausl
> * `rvvm ... -serial /tmp/pts1` brings the same UART over PTY/pipe path
> * `rvvm ... -serial stdout -serial /tmp/pts1 -serial /tmp/pts2` (Myriad of different uarts over different endpoints)
> 
> @iyzsong does this look good to you?
> 
> ![image](https://user-images.githubusercontent.com/50500857/235312683-8acef717-f4db-4936-883f-096d5305c213.png)

This kind of arguments design is good ,and is easy for the users(and me) to use.I will try them later.

**Comment by fish4terrisa-MSDSM** [comment]
> > Possible design of new RVVM arguments:
> > 
> > * `rvvm ...` brings UART over terminal as uausl
> > * `rvvm ... -serial /tmp/pts1` brings the same UART over PTY/pipe path
> > * `rvvm ... -serial stdout -serial /tmp/pts1 -serial /tmp/pts2` (Myriad of different uarts over different endpoints)
> > 
> > @iyzsong does this look good to you?
> > ![image](https://user-images.githubusercontent.com/50500857/235312683-8acef717-f4db-4936-883f-096d5305c213.png)
> 
> This kind of arguments design is good ,and is easy for the users(and me) to use.I will try them later.

That really work.Great! A new version of archriscv-term would be released soon.It helped me a lot,Thank you all. :D 
![Screenshot_20230430_212631](https://user-images.githubusercontent.com/63049888/235355344-82ba312e-43bc-4021-ba25-2babe363d2f6.jpg)
Thats a image of RVVM inside archriscv-term with multiple ttys.It\`s really convenient.

**Comment by LekKit** [comment]
Can we close the issue?

**Comment by fish4terrisa-MSDSM** [comment]
I think we can.It works now.
